.TH "/home/travis/build/yogeshg/clayer/src/analyser_test.cpp" 3 "Wed Mar 28 2018" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/src/analyser_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'property\&.h'\fP
.br
\fC#include 'analyser\&.h'\fP
.br
\fC#include 'logconfig\&.h'\fP
.br
\fC#include <regex>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrun\fP (std::string filename)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.SS "int run (std::stringfilename)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
