.TH "/home/travis/build/yogeshg/clayer/src/atm.cpp" 3 "Tue May 28 2019" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/src/atm.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'logconfig\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwithdraw\fP (int &account)"
.br
.ti -1c
.RI "void \fBdeposit\fP (int &account)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBiterations\fP = 1000"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void deposit (int &account)"

.SS "int main ()"

.SS "void withdraw (int &account)"

.SH "Variable Documentation"
.PP 
.SS "const int iterations = 1000"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
