.TH "clayer::analyser::DomainStat< p >" 3 "Thu Nov 28 2019" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clayer::analyser::DomainStat< p > \- 
.PP
This is a class that provides querying functionalities on \fBLogRecord\fP objects\&. We construct a \fBDomainStat\fP object based on a series of log_properties, taken in template arguments and group by the \fBLogRecord\fP objects based on such log_properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <analyser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDomainStat\fP ()=default"
.br
.RI "\fIThis is the default constructor that does nothing\&. \fP"
.ti -1c
.RI "\fBDomainStat\fP (std::vector< \fBLogRecord\fP > records, float precision=1\&.0, int outlier_count=10, float outlier_fraction=0\&.01)"
.br
.RI "\fIThis constuctor takes in a vector of \fBLogRecord\fP objects to perform analysis on, given the precision of the statistical analyser, the maximum count of ourliers that it identifies and the corresponding proportion of the ourliers\&. \fP"
.ti -1c
.RI "std::ostream & \fBto_string\fP (std::ostream &s)"
.br
.RI "\fIA helper function that prints a \fBDomainStat\fP objects to the output ostream\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, 
.br
\fButil::VectorStat\fP< float > > \fBdomain_stats\fP"
.br
.RI "\fIThis is a map that maps from a certain log_property typed string to a VectorStat object containing floats\&. We maintain this map to keep the result of the analysis\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<log_properties\&.\&.\&. p>class clayer::analyser::DomainStat< p >"
This is a class that provides querying functionalities on \fBLogRecord\fP objects\&. We construct a \fBDomainStat\fP object based on a series of log_properties, taken in template arguments and group by the \fBLogRecord\fP objects based on such log_properties\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<log_properties\&.\&.\&. p> \fBclayer::analyser::DomainStat\fP< p >::\fBDomainStat\fP ()\fC [default]\fP"

.PP
This is the default constructor that does nothing\&. 
.SS "template<log_properties\&.\&.\&. p> \fBclayer::analyser::DomainStat\fP< p >::\fBDomainStat\fP (std::vector< \fBLogRecord\fP >records, floatprecision = \fC1\&.0\fP, intoutlier_count = \fC10\fP, floatoutlier_fraction = \fC0\&.01\fP)\fC [inline]\fP"

.PP
This constuctor takes in a vector of \fBLogRecord\fP objects to perform analysis on, given the precision of the statistical analyser, the maximum count of ourliers that it identifies and the corresponding proportion of the ourliers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrecords\fP A vector containing \fBLogRecord\fP objects that \fBDomainStat\fP class will perform analysis on\&.
.br
\fIprecision\fP The precision factor that the statistical analyser relies on\&.
.br
\fIoutlier_count\fP Maximum number of outliers that \fBDomainStat\fP will identify from the records\&.
.br
\fIoutlier_fraction\fP Maximum proportion of outliers that \fBDomainStat\fP will identify from the records\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<log_properties\&.\&.\&. p> std::ostream& \fBclayer::analyser::DomainStat\fP< p >::to_string (std::ostream &s)\fC [inline]\fP"

.PP
A helper function that prints a \fBDomainStat\fP objects to the output ostream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP A std::ostream object that \fBDomainStat\fP will print to\&.
.RE
.PP
\fBReturns:\fP
.RS 4
std::ostream object that the function takes in\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<log_properties\&.\&.\&. p> std::map<std::string, \fButil::VectorStat\fP<float> > \fBclayer::analyser::DomainStat\fP< p >::domain_stats"

.PP
This is a map that maps from a certain log_property typed string to a VectorStat object containing floats\&. We maintain this map to keep the result of the analysis\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
