.TH "logger::hash::Flag< Val >" 3 "Sun Apr 30 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger::hash::Flag< Val > \- 
.PP
Template class for template overloading hash settings in logger stream operators\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBFlag\fP< Val > \fBinst\fP"
.br
.RI "\fIStatic singleton instances for the two boolean hash configuration states\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool Val>class logger::hash::Flag< Val >"
Template class for template overloading hash settings in logger stream operators\&. 


.PP
\fBRemarks:\fP
.RS 4
Private constructor so that only one instance of each class exists\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "template<bool Val> const \fBFlag\fP< Val > \fBlogger::hash::Flag\fP< Val >::inst\fC [static]\fP"

.PP
Static singleton instances for the two boolean hash configuration states\&. \fBLOG(INFO)\fP << \fBhash::on\fP << 'Amount: ' << \fBhash::off\fP << 20 << std::endl; 

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
