.TH "/home/travis/build/yogeshg/clayer/src/performance_test.cpp" 3 "Tue Aug 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/src/performance_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'stdlib\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br
\fC#include 'logconfig\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBworker\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBiterations\fP = 1000"
.br
.ti -1c
.RI "const int \fBthread_count\fP = 50"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "void worker ()"

.SH "Variable Documentation"
.PP 
.SS "const int iterations = 1000"
Performance test - multiple threads dumping log messages 
.SS "const int thread_count = 50"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
